# Problem 2: Even Fibonacci Numbers

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.

# Answer: 4613732
# Solved: 4/5/21

sum = 0 # Sum tracker

x = 1 # First integer
y = 1 # Second integer

while (y < 4000000):
    x, y = y, x + y # Iterates through the sequence
    
    if y % 2 == 0: # If even,
        sum += y # Add to sum

print(sum) # Prints answer